; Copyright 2026 Piyush Katariya
;
; Licensed under the Apache License, Version 2.0 (the "License");
; you may not use this file except in compliance with the License.
; You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.

; Tests for universe_encoding_flatbuffers_*: a hand-crafted KAT flatbuffer
; (a table with i32=-42, f64=3.14159, string "hello", vector<i32>[10,20,30],
; and an absent 5th field) with every accessor asserted against the known
; values; a size-prefixed twin; a REAL Arrow IPC Message flatbuffer sliced from
; tests/fixtures/flat.arrow, whose Schema (header type 1, fields.length 4,
; version 5, endianness/bodyLength absent-default 0) is decoded through the same
; accessors as an external ground truth; error paths (short buffer, OOB scalar
; read, malformed string, vector_elem overflow, null out) returning 8/1/-1; and
; a truncate/mutate fuzz loop whose status invariants hold under ASan.

; ---- module under test ----
declare i64 @universe_encoding_flatbuffers_root(ptr, i64)
declare i64 @universe_encoding_flatbuffers_sized_root(ptr, i64)
declare i64 @universe_encoding_flatbuffers_field(ptr, i64, i64, i32)
declare i32 @universe_encoding_flatbuffers_read_i8(ptr, i64, i64, i8, ptr)
declare i32 @universe_encoding_flatbuffers_read_u8(ptr, i64, i64, i8, ptr)
declare i32 @universe_encoding_flatbuffers_read_i16(ptr, i64, i64, i16, ptr)
declare i32 @universe_encoding_flatbuffers_read_u16(ptr, i64, i64, i16, ptr)
declare i32 @universe_encoding_flatbuffers_read_i32(ptr, i64, i64, i32, ptr)
declare i32 @universe_encoding_flatbuffers_read_u32(ptr, i64, i64, i32, ptr)
declare i32 @universe_encoding_flatbuffers_read_i64(ptr, i64, i64, i64, ptr)
declare i32 @universe_encoding_flatbuffers_read_u64(ptr, i64, i64, i64, ptr)
declare i32 @universe_encoding_flatbuffers_read_f32(ptr, i64, i64, float, ptr)
declare i32 @universe_encoding_flatbuffers_read_f64(ptr, i64, i64, double, ptr)
declare i64 @universe_encoding_flatbuffers_indirect(ptr, i64, i64)
declare i32 @universe_encoding_flatbuffers_string(ptr, i64, i64, ptr, ptr)
declare i32 @universe_encoding_flatbuffers_vector(ptr, i64, i64, ptr, ptr)
declare i64 @universe_encoding_flatbuffers_vector_elem(i64, i32, i64)

declare i32 @memcmp(ptr, ptr, i64)

declare void @ut_check(i1, ptr)
declare void @ut_check_eq(i64, i64, ptr)
declare i64 @ut_rand(ptr)
declare double @ut_now_sec()
declare i1 @ut_want_bench(i32, ptr)
declare void @ut_report_dist(ptr, i64, i64, ptr)
declare i32 @ut_summary()

; ---- KAT flatbuffer (68 bytes), generated by python from the wire spec:
;   table @18: f0 i32=-42, f1 f64=3.14159, f2 string "hello", f3 vec<i32>[10,20,30]
@kat = private unnamed_addr constant [68 x i8] c"\12\00\00\00\0E\00\18\00\04\00\08\00\10\00\14\00\00\00\0E\00\00\00\D6\FF\FF\FF\6E\86\1B\F0\F9\21\09\40\08\00\00\00\0E\00\00\00\05\00\00\00\68\65\6C\6C\6F\00\03\00\00\00\0A\00\00\00\14\00\00\00\1E\00\00\00"
; size-prefixed twin (u32 size=68 ++ kat) = 72 bytes; table @22
@kat_sp = private unnamed_addr constant [72 x i8] c"\44\00\00\00\12\00\00\00\0E\00\18\00\04\00\08\00\10\00\14\00\00\00\0E\00\00\00\D6\FF\FF\FF\6E\86\1B\F0\F9\21\09\40\08\00\00\00\0E\00\00\00\05\00\00\00\68\65\6C\6C\6F\00\03\00\00\00\0A\00\00\00\14\00\00\00\1E\00\00\00"
; real Arrow IPC Message flatbuffer (256 bytes) sliced from flat.arrow @8
@arrow = private unnamed_addr constant [256 x i8] c"\08\00\00\00\00\00\00\00\16\FF\FF\FF\04\00\01\00\04\00\00\00\2E\FF\FF\FF\14\00\00\00\0C\00\00\00\04\00\00\00\00\00\00\00\00\00\00\00\04\00\00\00\74\00\00\00\50\00\00\00\28\00\00\00\04\00\00\00\70\FF\FF\FF\10\00\00\00\01\06\00\00\04\00\00\00\74\FF\FF\FF\04\00\00\00\66\6C\61\67\00\00\00\00\90\FF\FF\FF\14\00\00\00\01\03\00\00\04\00\00\00\90\FF\FF\FF\02\00\00\00\05\00\00\00\73\63\6F\72\65\00\00\00\B4\FF\FF\FF\10\00\00\00\01\05\00\00\04\00\00\00\B8\FF\FF\FF\04\00\00\00\6E\61\6D\65\00\00\00\00\D4\FF\FF\FF\18\00\00\00\01\02\00\00\04\00\00\00\EC\FF\FF\FF\40\00\00\00\01\00\00\00\02\00\00\00\69\64\00\00\08\00\09\00\04\00\08\00\0C\00\10\00\04\00\08\00\09\00\0C\00\04\00\04\00\06\00\06\00\04\00\0C\00\10\00\00\00\04\00\08\00\0C\00\0A\00\0C\00\04\00\06\00\08\00\00\00\00\00"

@hello = private unnamed_addr constant [5 x i8] c"hello"

@g.buf = internal global [80 x i8] zeroinitializer, align 8
@g.out = internal global i64 0, align 8

; ---- messages ----
@m.root  = private unnamed_addr constant [16 x i8] c"kat root == 18 \00"
@m.f0    = private unnamed_addr constant [16 x i8] c"kat f0 i32 -42 \00"
@m.f1    = private unnamed_addr constant [16 x i8] c"kat f1 f64 pi  \00"
@m.f2    = private unnamed_addr constant [16 x i8] c"kat f2 str len \00"
@m.f2v   = private unnamed_addr constant [16 x i8] c"kat f2 == hello\00"
@m.f3    = private unnamed_addr constant [16 x i8] c"kat f3 vec cnt \00"
@m.f3e   = private unnamed_addr constant [16 x i8] c"kat f3 elems   \00"
@m.absent= private unnamed_addr constant [16 x i8] c"kat f4 absent  \00"
@m.dflt  = private unnamed_addr constant [16 x i8] c"kat f4 default \00"
@m.oob   = private unnamed_addr constant [16 x i8] c"absent id 5    \00"
@m.u8    = private unnamed_addr constant [16 x i8] c"read_u8 'h'    \00"
@m.u16   = private unnamed_addr constant [16 x i8] c"read_u16 vtsz  \00"
@m.u64   = private unnamed_addr constant [16 x i8] c"read_u64 bits  \00"
@m.f64d  = private unnamed_addr constant [16 x i8] c"read_f64 dflt  \00"
@m.f32d  = private unnamed_addr constant [16 x i8] c"read_f32 dflt  \00"
@m.sp    = private unnamed_addr constant [16 x i8] c"sized_root ==22\00"
@m.spf0  = private unnamed_addr constant [16 x i8] c"sized f0 == -42\00"
@m.ar    = private unnamed_addr constant [16 x i8] c"arrow root == 8\00"
@m.arht  = private unnamed_addr constant [16 x i8] c"arrow hdr==Schm\00"
@m.arsc  = private unnamed_addr constant [16 x i8] c"arrow schema@20\00"
@m.arfc  = private unnamed_addr constant [16 x i8] c"arrow fields==4\00"
@m.aren  = private unnamed_addr constant [16 x i8] c"arrow endian 0 \00"
@m.arver = private unnamed_addr constant [16 x i8] c"arrow ver == 5 \00"
@m.arbl  = private unnamed_addr constant [16 x i8] c"arrow body == 0\00"
@m.eshort= private unnamed_addr constant [17 x i8] c"short root -> -1\00"
@m.eoob  = private unnamed_addr constant [16 x i8] c"scalar OOB -> 8\00"
@m.estr  = private unnamed_addr constant [16 x i8] c"str trunc -> 8 \00"
@m.evel  = private unnamed_addr constant [16 x i8] c"vec_elem ovf -1\00"
@m.enull = private unnamed_addr constant [16 x i8] c"null out -> 1  \00"
@m.fuzz  = private unnamed_addr constant [20 x i8] c"fuzz status inv    \00"
@lbl.dec = private unnamed_addr constant [21 x i8] c"flatbuffers navigate\00"

@vi.samp = internal global [16 x double] zeroinitializer, align 8

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %v32   = alloca i32, align 4
  %v64   = alloca i64, align 8
  %v16   = alloca i16, align 2
  %v8    = alloca i8, align 1
  %dbits = alloca i64, align 8
  %sptr  = alloca ptr, align 8
  %slen  = alloca i64, align 8
  %vstart= alloca i64, align 8
  %vcount= alloca i64, align 8

  ; ================= KAT =================
  %root = call i64 @universe_encoding_flatbuffers_root(ptr @kat, i64 68)
  %root.ok = icmp eq i64 %root, 18
  call void @ut_check(i1 %root.ok, ptr @m.root)

  ; f0: i32 = -42
  %f0 = call i64 @universe_encoding_flatbuffers_field(ptr @kat, i64 68, i64 %root, i32 0)
  %r0 = call i32 @universe_encoding_flatbuffers_read_i32(ptr @kat, i64 68, i64 %f0, i32 0, ptr %v32)
  %val0 = load i32, ptr %v32, align 4
  %v0.ok = icmp eq i32 %val0, -42
  %r0.ok = icmp eq i32 %r0, 0
  %f0.ok = and i1 %v0.ok, %r0.ok
  call void @ut_check(i1 %f0.ok, ptr @m.f0)

  ; f1: f64 = 3.14159 (compare raw bits: 0x400921F9F01B866E)
  %f1 = call i64 @universe_encoding_flatbuffers_field(ptr @kat, i64 68, i64 %root, i32 1)
  %r1 = call i32 @universe_encoding_flatbuffers_read_f64(ptr @kat, i64 68, i64 %f1, double 0.0, ptr %v64)
  %val1 = load i64, ptr %v64, align 8
  %v1.ok = icmp eq i64 %val1, 4614256650576692846
  %r1.ok = icmp eq i32 %r1, 0
  %f1.ok = and i1 %v1.ok, %r1.ok
  call void @ut_check(i1 %f1.ok, ptr @m.f1)

  ; f2: string "hello"
  %f2 = call i64 @universe_encoding_flatbuffers_field(ptr @kat, i64 68, i64 %root, i32 2)
  %rs = call i32 @universe_encoding_flatbuffers_string(ptr @kat, i64 68, i64 %f2, ptr %sptr, ptr %slen)
  %sl = load i64, ptr %slen, align 8
  %sl.ok = icmp eq i64 %sl, 5
  %rs.ok = icmp eq i32 %rs, 0
  %f2.ok = and i1 %sl.ok, %rs.ok
  call void @ut_check(i1 %f2.ok, ptr @m.f2)
  %sp = load ptr, ptr %sptr, align 8
  %scmp = call i32 @memcmp(ptr %sp, ptr @hello, i64 5)
  %scmp.ok = icmp eq i32 %scmp, 0
  call void @ut_check(i1 %scmp.ok, ptr @m.f2v)

  ; f3: vector<i32>[10,20,30]
  %f3 = call i64 @universe_encoding_flatbuffers_field(ptr @kat, i64 68, i64 %root, i32 3)
  %rv = call i32 @universe_encoding_flatbuffers_vector(ptr @kat, i64 68, i64 %f3, ptr %vstart, ptr %vcount)
  %vc = load i64, ptr %vcount, align 8
  %vc.ok = icmp eq i64 %vc, 3
  %rv.ok = icmp eq i32 %rv, 0
  %f3.ok = and i1 %vc.ok, %rv.ok
  call void @ut_check(i1 %f3.ok, ptr @m.f3)
  %vs = load i64, ptr %vstart, align 8
  ; elem 0
  %e0l = call i64 @universe_encoding_flatbuffers_vector_elem(i64 %vs, i32 4, i64 0)
  %e0r = call i32 @universe_encoding_flatbuffers_read_i32(ptr @kat, i64 68, i64 %e0l, i32 0, ptr %v32)
  %e0 = load i32, ptr %v32, align 4
  ; elem 1
  %e1l = call i64 @universe_encoding_flatbuffers_vector_elem(i64 %vs, i32 4, i64 1)
  %e1r = call i32 @universe_encoding_flatbuffers_read_i32(ptr @kat, i64 68, i64 %e1l, i32 0, ptr %v32)
  %e1 = load i32, ptr %v32, align 4
  ; elem 2
  %e2l = call i64 @universe_encoding_flatbuffers_vector_elem(i64 %vs, i32 4, i64 2)
  %e2r = call i32 @universe_encoding_flatbuffers_read_i32(ptr @kat, i64 68, i64 %e2l, i32 0, ptr %v32)
  %e2 = load i32, ptr %v32, align 4
  %e0.ok = icmp eq i32 %e0, 10
  %e1.ok = icmp eq i32 %e1, 20
  %e2.ok = icmp eq i32 %e2, 30
  %e01 = and i1 %e0.ok, %e1.ok
  %e012 = and i1 %e01, %e2.ok
  call void @ut_check(i1 %e012, ptr @m.f3e)

  ; f4: absent (voffset 0 in vtable) -> field returns -1
  %f4 = call i64 @universe_encoding_flatbuffers_field(ptr @kat, i64 68, i64 %root, i32 4)
  %f4.ok = icmp eq i64 %f4, -1
  call void @ut_check(i1 %f4.ok, ptr @m.absent)
  ; reading an absent field yields the caller's default
  %r4 = call i32 @universe_encoding_flatbuffers_read_i32(ptr @kat, i64 68, i64 %f4, i32 -777, ptr %v32)
  %val4 = load i32, ptr %v32, align 4
  %v4.ok = icmp eq i32 %val4, -777
  %r4.ok = icmp eq i32 %r4, 0
  %f4d.ok = and i1 %v4.ok, %r4.ok
  call void @ut_check(i1 %f4d.ok, ptr @m.dflt)

  ; field id 5 (>= field_count 5) -> absent -1
  %f5 = call i64 @universe_encoding_flatbuffers_field(ptr @kat, i64 68, i64 %root, i32 5)
  %f5.ok = icmp eq i64 %f5, -1
  call void @ut_check(i1 %f5.ok, ptr @m.oob)

  ; read_u8 of the first string byte 'h' (0x68=104) at loc 46
  %u8r = call i32 @universe_encoding_flatbuffers_read_u8(ptr @kat, i64 68, i64 46, i8 0, ptr %v8)
  %u8v = load i8, ptr %v8, align 1
  %u8.ok = icmp eq i8 %u8v, 104
  call void @ut_check(i1 %u8.ok, ptr @m.u8)

  ; read_u16 of vtable_size (14) at loc 4
  %u16r = call i32 @universe_encoding_flatbuffers_read_u16(ptr @kat, i64 68, i64 4, i16 0, ptr %v16)
  %u16v = load i16, ptr %v16, align 2
  %u16.ok = icmp eq i16 %u16v, 14
  call void @ut_check(i1 %u16.ok, ptr @m.u16)

  ; read_u64 of the f64 bit pattern at loc 26
  %u64r = call i32 @universe_encoding_flatbuffers_read_u64(ptr @kat, i64 68, i64 26, i64 0, ptr %v64)
  %u64v = load i64, ptr %v64, align 8
  %u64.ok = icmp eq i64 %u64v, 4614256650576692846
  call void @ut_check(i1 %u64.ok, ptr @m.u64)

  ; read_f64 default (absent loc) -> 2.5 (bits 0x4004000000000000)
  %fdr = call i32 @universe_encoding_flatbuffers_read_f64(ptr @kat, i64 68, i64 -1, double 2.5, ptr %v64)
  %fdv = load i64, ptr %v64, align 8
  %fd.ok = icmp eq i64 %fdv, 4612811918334230528
  call void @ut_check(i1 %fd.ok, ptr @m.f64d)

  ; read_f32 default (absent loc) -> 1.5 (bits 0x3FC00000)
  %f3r = call i32 @universe_encoding_flatbuffers_read_f32(ptr @kat, i64 68, i64 -1, float 1.5, ptr %v32)
  %f3v = load i32, ptr %v32, align 4
  %f32.ok = icmp eq i32 %f3v, 1069547520
  call void @ut_check(i1 %f32.ok, ptr @m.f32d)

  ; ================= size-prefixed =================
  %sroot = call i64 @universe_encoding_flatbuffers_sized_root(ptr @kat_sp, i64 72)
  %sroot.ok = icmp eq i64 %sroot, 22
  call void @ut_check(i1 %sroot.ok, ptr @m.sp)
  %spf0 = call i64 @universe_encoding_flatbuffers_field(ptr @kat_sp, i64 72, i64 %sroot, i32 0)
  %spr0 = call i32 @universe_encoding_flatbuffers_read_i32(ptr @kat_sp, i64 72, i64 %spf0, i32 0, ptr %v32)
  %spval0 = load i32, ptr %v32, align 4
  %spf0.ok = icmp eq i32 %spval0, -42
  call void @ut_check(i1 %spf0.ok, ptr @m.spf0)

  ; ================= real Arrow Message (external oracle) =================
  %aroot = call i64 @universe_encoding_flatbuffers_root(ptr @arrow, i64 256)
  %aroot.ok = icmp eq i64 %aroot, 8
  call void @ut_check(i1 %aroot.ok, ptr @m.ar)
  ; header type (field 1) == 1 (Schema)
  %aht = call i64 @universe_encoding_flatbuffers_field(ptr @arrow, i64 256, i64 %aroot, i32 1)
  %ahtr = call i32 @universe_encoding_flatbuffers_read_u8(ptr @arrow, i64 256, i64 %aht, i8 0, ptr %v8)
  %ahtv = load i8, ptr %v8, align 1
  %aht.ok = icmp eq i8 %ahtv, 1
  call void @ut_check(i1 %aht.ok, ptr @m.arht)
  ; header value (field 2) -> indirect -> Schema table @ 20
  %ahv = call i64 @universe_encoding_flatbuffers_field(ptr @arrow, i64 256, i64 %aroot, i32 2)
  %aschema = call i64 @universe_encoding_flatbuffers_indirect(ptr @arrow, i64 256, i64 %ahv)
  %asc.ok = icmp eq i64 %aschema, 20
  call void @ut_check(i1 %asc.ok, ptr @m.arsc)
  ; Schema.fields (field 1) vector length == 4
  %afl = call i64 @universe_encoding_flatbuffers_field(ptr @arrow, i64 256, i64 %aschema, i32 1)
  %afv = call i32 @universe_encoding_flatbuffers_vector(ptr @arrow, i64 256, i64 %afl, ptr %vstart, ptr %vcount)
  %afc = load i64, ptr %vcount, align 8
  %afc.ok = icmp eq i64 %afc, 4
  %afv.ok = icmp eq i32 %afv, 0
  %af.ok = and i1 %afc.ok, %afv.ok
  call void @ut_check(i1 %af.ok, ptr @m.arfc)
  ; Schema.endianness (field 0) absent -> default 0 (little)
  %aen = call i64 @universe_encoding_flatbuffers_field(ptr @arrow, i64 256, i64 %aschema, i32 0)
  %aenr = call i32 @universe_encoding_flatbuffers_read_i16(ptr @arrow, i64 256, i64 %aen, i16 0, ptr %v16)
  %aenv = load i16, ptr %v16, align 2
  %aen.ok = icmp eq i16 %aenv, 0
  call void @ut_check(i1 %aen.ok, ptr @m.aren)
  ; Message.version (field 0) == 5 (MetadataVersion V5)
  %aver = call i64 @universe_encoding_flatbuffers_field(ptr @arrow, i64 256, i64 %aroot, i32 0)
  %averr = call i32 @universe_encoding_flatbuffers_read_i16(ptr @arrow, i64 256, i64 %aver, i16 0, ptr %v16)
  %averv = load i16, ptr %v16, align 2
  %aver.ok = icmp eq i16 %averv, 4
  call void @ut_check(i1 %aver.ok, ptr @m.arver)
  ; Message.bodyLength (field 3) absent -> default 0
  %abl = call i64 @universe_encoding_flatbuffers_field(ptr @arrow, i64 256, i64 %aroot, i32 3)
  %ablr = call i32 @universe_encoding_flatbuffers_read_i64(ptr @arrow, i64 256, i64 %abl, i64 0, ptr %v64)
  %ablv = load i64, ptr %v64, align 8
  %abl.ok = icmp eq i64 %ablv, 0
  call void @ut_check(i1 %abl.ok, ptr @m.arbl)

  ; ================= error paths =================
  ; short buffer: len 2 < 4 -> root returns -1
  %esr = call i64 @universe_encoding_flatbuffers_root(ptr @kat, i64 2)
  %esr.ok = icmp eq i64 %esr, -1
  call void @ut_check(i1 %esr.ok, ptr @m.eshort)
  ; OOB scalar read: loc 66, 66+4=70 > 68 -> 8
  %eo = call i32 @universe_encoding_flatbuffers_read_i32(ptr @kat, i64 68, i64 66, i32 0, ptr %v32)
  %eo.ok = icmp eq i32 %eo, 8
  call void @ut_check(i1 %eo.ok, ptr @m.eoob)
  ; malformed string: truncate the buffer len so the string data escapes -> 8
  %est = call i32 @universe_encoding_flatbuffers_string(ptr @kat, i64 48, i64 34, ptr %sptr, ptr %slen)
  %est.ok = icmp eq i32 %est, 8
  call void @ut_check(i1 %est.ok, ptr @m.estr)
  ; vector_elem overflow: huge stride*index -> -1
  %ev = call i64 @universe_encoding_flatbuffers_vector_elem(i64 8, i32 -1, i64 -1)
  %ev.ok = icmp eq i64 %ev, -1
  call void @ut_check(i1 %ev.ok, ptr @m.evel)
  ; null out pointer -> 1
  %en = call i32 @universe_encoding_flatbuffers_read_i32(ptr @kat, i64 68, i64 %f0, i32 0, ptr null)
  %en.ok = icmp eq i32 %en, 1
  call void @ut_check(i1 %en.ok, ptr @m.enull)

  ; ================= fuzz: truncate/mutate, status invariants hold =================
  ; Fill g.buf with random bytes, root over a random-length prefix, then drive
  ; field/read/string/vector; every i32 return must be 0/1/8, every loc >= -1.
  ; ASan proves no OOB; here we assert the documented-code invariant.
  %state = alloca i64, align 8
  store i64 987654321, ptr %state, align 8
  br label %fz.head

fz.head:
  %fi = phi i64 [ 0, %entry ], [ %fi.n, %fz.tail ]
  %fbad = phi i64 [ 0, %entry ], [ %fbad.n, %fz.tail ]
  ; randomize 80 bytes (10 words)
  br label %fill.head
fill.head:
  %wi = phi i64 [ 0, %fz.head ], [ %wi.n, %fill.head ]
  %rw = call i64 @ut_rand(ptr %state)
  %wp = getelementptr inbounds [80 x i8], ptr @g.buf, i64 0, i64 0
  %wpp = getelementptr inbounds i64, ptr %wp, i64 %wi
  store i64 %rw, ptr %wpp, align 8
  %wi.n = add nuw i64 %wi, 1
  %wmore = icmp ult i64 %wi.n, 10
  br i1 %wmore, label %fill.head, label %fz.body
fz.body:
  %frl = call i64 @ut_rand(ptr %state)
  %flen = urem i64 %frl, 81            ; 0..80
  %fr = call i64 @universe_encoding_flatbuffers_root(ptr @g.buf, i64 %flen)
  ; pick a random field id 0..7
  %frid = call i64 @ut_rand(ptr %state)
  %fid = urem i64 %frid, 8
  %fid32 = trunc i64 %fid to i32
  %ff = call i64 @universe_encoding_flatbuffers_field(ptr @g.buf, i64 %flen, i64 %fr, i32 %fid32)
  ; scalar read at the field loc
  %rr = call i32 @universe_encoding_flatbuffers_read_i64(ptr @g.buf, i64 %flen, i64 %ff, i64 0, ptr @g.out)
  ; string + vector at the field loc
  %rstr = call i32 @universe_encoding_flatbuffers_string(ptr @g.buf, i64 %flen, i64 %ff, ptr %sptr, ptr %slen)
  %rvec = call i32 @universe_encoding_flatbuffers_vector(ptr @g.buf, i64 %flen, i64 %ff, ptr %vstart, ptr %vcount)
  ; indirect at the field loc
  %find = call i64 @universe_encoding_flatbuffers_indirect(ptr @g.buf, i64 %flen, i64 %ff)
  ; status invariants: reads in {0,1,8}; locs >= -1
  %rr0 = icmp eq i32 %rr, 0
  %rr1 = icmp eq i32 %rr, 1
  %rr8 = icmp eq i32 %rr, 8
  %rr01 = or i1 %rr0, %rr1
  %rrok = or i1 %rr01, %rr8
  %rs0 = icmp eq i32 %rstr, 0
  %rs1 = icmp eq i32 %rstr, 1
  %rs8 = icmp eq i32 %rstr, 8
  %rs01 = or i1 %rs0, %rs1
  %rsok = or i1 %rs01, %rs8
  %rv0 = icmp eq i32 %rvec, 0
  %rv1 = icmp eq i32 %rvec, 1
  %rv8 = icmp eq i32 %rvec, 8
  %rv01 = or i1 %rv0, %rv1
  %rvok = or i1 %rv01, %rv8
  %loc.ok = icmp sge i64 %ff, -1
  %ind.ok = icmp sge i64 %find, -1
  %root.ge = icmp sge i64 %fr, -1
  %a = and i1 %rrok, %rsok
  %b = and i1 %a, %rvok
  %c = and i1 %b, %loc.ok
  %d = and i1 %c, %ind.ok
  %allok = and i1 %d, %root.ge
  %badb = xor i1 %allok, true
  %badz = zext i1 %badb to i64
  %fbad.n = add nuw i64 %fbad, %badz
  br label %fz.tail
fz.tail:
  %fi.n = add nuw i64 %fi, 1
  %fmore = icmp ult i64 %fi.n, 100000
  br i1 %fmore, label %fz.head, label %fz.done
fz.done:
  call void @ut_check_eq(i64 %fbad, i64 0, ptr @m.fuzz)

  ; ================= bench =================
  %wb = call i1 @ut_want_bench(i32 %argc, ptr %argv)
  br i1 %wb, label %bench, label %fin

bench:
  br label %b.rep
b.rep:
  %brep = phi i64 [ 0, %bench ], [ %brep.n, %b.next ]
  %bt0 = call double @ut_now_sec()
  br label %b.loop
b.loop:
  %bc = phi i64 [ 0, %b.rep ], [ %bc.n, %b.loop ]
  %broot = call i64 @universe_encoding_flatbuffers_root(ptr @kat, i64 68)
  %bf = call i64 @universe_encoding_flatbuffers_field(ptr @kat, i64 68, i64 %broot, i32 0)
  %br = call i32 @universe_encoding_flatbuffers_read_i32(ptr @kat, i64 68, i64 %bf, i32 0, ptr @g.out)
  %bc.n = add nuw i64 %bc, 1
  %bmore = icmp ult i64 %bc.n, 1000000
  br i1 %bmore, label %b.loop, label %b.rep.done
b.rep.done:
  %bt1 = call double @ut_now_sec()
  %bel = fsub double %bt1, %bt0
  %bkeep = icmp ugt i64 %brep, 0
  br i1 %bkeep, label %b.store, label %b.next
b.store:
  %bidx = sub i64 %brep, 1
  %bsp = getelementptr inbounds [16 x double], ptr @vi.samp, i64 0, i64 %bidx
  store double %bel, ptr %bsp, align 8
  br label %b.next
b.next:
  %brep.n = add nuw i64 %brep, 1
  %brm = icmp ult i64 %brep.n, 17
  br i1 %brm, label %b.rep, label %b.report
b.report:
  call void @ut_report_dist(ptr @vi.samp, i64 16, i64 1000000, ptr @lbl.dec)
  br label %fin

fin:
  %code = call i32 @ut_summary()
  ret i32 %code
}
